### PR TITLE
Add Emoji Hands for scale

### PR DESCRIPTION
**Pull request by 3raxton**
I believe I've done all of this correctly - the only think I'm unsure about is the detents within the addition but otherwise, let me know what you think!

### CODE REVIEW

**Comment by brianmichel** [comment]
Hey @3raxton looks good, but you'll need to call this function in the `makeApplicationDefaults` function if you want your scale to show up in the list.

**Comment by brianmichel** [comment]
@3raxton this code does not compile. You need to give your function a name that does not already exist. `makeEmojiScale` is already the name of a function so you cannot reuse that same name. Perhaps rename it to `makeEmojiHandsScale` instead?

**Comment by 3raxton** [comment]
Apologies. Thanks to my sleep loss I had assumed that emojis would be fine and didn't double check. Hopefully, this compiles!

**Comment by brianmichel** [comment]
LGTM 👍 thanks @3raxton I'll do a release after I merge this.

**Comment by 3raxton** [comment]
Brilliant! Thank you immensely for your guidance!

**Pull request merged**
